version: '3.2'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    image: mariusrugan/articles_app:dev
    volumes:
      - ../../app/src:/app/src
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      NODE_ENV: development
      POSTGRES_HOST: db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db_articles

  db:
    image: postgres
    hostname: db
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db_articles
